services:
  - type: web
    name: kadrio-site
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_TOKEN
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: SINGLE_PRODUCT_NAME
        value: Kadrio Tek Ürün
      - key: SINGLE_PRODUCT_PRICE
        value: "99"
      - key: PAYMENT_LINK_URL
        value: https://www.shopier.com/kadrio/50337921
